### ISSUE TITLE
A database connection failure causes the last message to be processed again (via a retry)

### ISSUE THREAD

**Issue by claytona-armstrong5** [Shuttle/Shuttle.Esb.Sql.Queue#2]
Hi Eben,

Apologies for logging an issue/question in the holiday season... I'll understand if you are unable to respond as quickly as you normally do! :)

We are experiencing quite a strange issue.  On several occasions, it appears that one or more of our services in production (all using Shuttle) have done the following:

1. Logged an ERROR message, indicating an exception trying to poll the database for new messages (we are using the SQL Server queue implementation).  The error we get is "The specified network name is no longer available", which I believe to be related to something happening with our infrastructure (outside the application's control)

2. Logged a DEBUG message a short time later, reflecting the same error details as for the original exception above

3. Immediately after the above, logged a WARN message containing details of a failed message handler. At the end of this message is text like "It is retry number: 1 / 5".

4. After the initial retry period since (3) has elapsed (ie default of 5 minutes), the service then tries to process the message again... and it works.

The very strange thing is that the messages that are being processed as part of the above cycle are old messages, that have been processed one to five days ago.  We've know this because in some cases we log the message GUIDs to our log files, and we've matched up the new exceptions with messages that occurred days ago, and which were processed without any error at all.

So while the initial catalyst appears to be an infrastructure issue (out of our control), the services then appear to process old messages.

An example log extract where the above has occurred is as follows. In this example, the message being retried, "a416fa3e-dc90-4706-9b94-fb157bde362b", was from four days earlier:
```
2017-12-24 20:19:01,708 ERROR [InboxProcessor / 1] Shuttle.Esb.Sql.Queue.SqlQueue.Error - Could not dequeue message from queue 'sql://messaging/payments-work'.  Exception: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The specified network name is no longer available.).  Query: Shuttle.Core.Data.RawQuery
2017-12-24 20:19:08,238 DEBUG [InboxProcessor / 1] Racti.Common.Shuttle.ServiceBusFactory.<Setup>b__4_0 - BeforePipelineExceptionHandled: Shuttle.Core.Infrastructure.PipelineException: Raising pipeline event 'Shuttle.Esb.OnGetMessage' in stage 'Read' for observer 'Shuttle.Esb.GetWorkMessageObserver'. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The specified network name is no longer available.) ---> System.ComponentModel.Win32Exception: The specified network name is no longer available
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Shuttle.Core.Data.DatabaseGateway.GetReaderUsing(IQuery query)
   at Shuttle.Core.Data.DatabaseGateway.GetDataTableFor(IQuery query)
   at Shuttle.Core.Data.DatabaseGateway.GetSingleRowUsing(IQuery query)
   at Shuttle.Esb.Sql.Queue.SqlQueue.GetMessage()
   at Shuttle.Esb.GetWorkMessageObserver.Execute(OnGetMessage pipelineEvent)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Shuttle.Core.Infrastructure.Pipeline.RaiseEvent(IPipelineEvent event, Boolean ignoreAbort)
   --- End of inner exception stack trace ---
   at Shuttle.Core.Infrastructure.Pipeline.RaiseEvent(IPipelineEvent event, Boolean ignoreAbort)
   at Shuttle.Core.Infrastructure.Pipeline.Execute()
2017-12-24 20:19:08,347 WARN [InboxProcessor / 1] Shuttle.Esb.ReceiveExceptionObserver.Warning - Message handler type 'PaymentsService.Commands.ProcessAcknowledgedPayables.Handler' raised exception 'Raising pipeline event 'Shuttle.Esb.OnGetMessage' in stage 'Read' for observer 'Shuttle.Esb.GetWorkMessageObserver'. / Exception has been thrown by the target of an invocation. / A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The specified network name is no longer available.) / The specified network name is no longer available'.  Handling of message type 'FileActive.Messages.Commands.ProcessAcknowledgedPayables' with id 'a416fa3e-dc90-4706-9b94-fb157bde362b' will be retried.  It is retry number: 1 / 5
2017-12-24 20:24:09,161 INFO [InboxProcessor / 1] PaymentsService.MessageHandlerBase`1.ProcessMessage - Start ProcessAcknowledgedPayables
```

We've witnessed this behaviour on several occasions in production.  The most recent was on Christmas Eve.  We had three separate services all do exactly the same thing, at exactly the same time (presumably due to a single infrastructure issue), and try to process messages that had already been processed days ago.

Do you recall if there is any message caching that might explain this behaviour?
I've been looking at the code in SqlQueue... but don't yet have any theories on what might be happening.

I'm aware we are taking incremental database backups every minute, and I suspect we were backing up the VM at the time of our most recent incident, but I'm not sure how this could be triggering the services to process old messages.

If you have time to have a quick think about this and offer insights or things to investigate it would be greatly appreciated

Many thanks,
Clayton

**Comment by eben-roux** [comment]
Hi Clayton,

I am actually using my holiday period (16 Dec 2017 to 7 Jan 2018) to work on Shuttle.  I am including .Net Core in the mix.  Also have some supporting projects I am working on.

Anyway, back to your issue.

There is no message caching that I am aware of.  Implementing some basic idempotence is always a win.  Is it at all possible that the message ids are being assigned so that they look old but are actually new?  Old messages should not be appearing again... that's for sure.

It *may* be a publisher somewhere in the business process?

The only thing I could suggest is using the [message forwarding](https://www.nuget.org/packages/Shuttle.Esb.Module.MessageForwarding/) and then inspecting the troublesome messages.  The `TransportMessage` envelope will give you some clues w.r.t. sender and time sent, etc.

Hopefully I'll get some time to work on my [Shuttle.Sentinel](https://github.com/Shuttle/Shuttle.Sentinel) project as that will enable you to have a closer look at those messages.  I think the `DumpMessages` application in the [Shuttle.Esb.Tools](https://github.com/Shuttle/Shuttle.Esb.Tools) repository may also help.

Please let me know how you get on.

Regards,
Eben

**Comment by claytona-armstrong5** [comment]
Okay, many thanks for responding so quickly again Eben :)

I'm sure the messages were not new.  I can tell from their content that they were from days earlier. Also, a lot of our messaging orchestrations are initiated by scheduled jobs, and each command or event type normally occurs within a specific time period.  At the time of the incident, no messages were being sent... The issue appears to have triggered solely due to the infrastructure issue. ie services were doing nothing, infrastructure issue occurs, and then three services immediately process old messages.
Re idempotence... yes good point. We've made some of our messages idempotent, but unfortunately not all.
Re message forwarding, thanks for that tip... I was not aware of that library.

I'll continue to think about what might be happening... if I find anything I'll be sure to let you know, even if (as is likely) it's nothing to do with Shuttle

Cheers,
Clayton

**Comment by claytona-armstrong5** [comment]
An update on this Eben...

It actually does appear to be a problem in Shuttle. 
I've managed to reproduce it with the following steps:

- Start a shuttle service
- Let it process some messages
- Kill the service's database connection

The service will then reschedule the last message it processed for a retry, even though it was already completely processed.  
I was doing a similar test yesterday, but did not repro the problem as I was restarting SQL Server, rather than ungraciously killing the connection. So killing the connection unexpectedly makes a difference.

I've been looking at the code in "ReceiveExceptionObserver", and it gets the current transport message from the pipeline state.  If the transport message is null, an error is logged, and there is no retry. But if it's not null, and the exception was not an unrecoverablehandlerexception, it will schedule a retry.

I'm guessing that when the issue occurs, the transport message is not null, and is instead the last message that was successfully processed by the service.  

I've noticed that the pipeline state bag has a "Clear()" method, although I couldn't spot any references to that.  I'm not sure, but maybe the entries only get overwritten with calls to the various "Replace()" methods?  If that's the case, that would mean the transport message was not actually cleared out until a new message came into replace it?

Is it possible that the last transport message is never getting cleared out of the pipeline state?

**Comment by eben-roux** [comment]
Thanks for the feedback Clayton,

The error may cause some oddities so I'll look into your scenario.  The state is cleared on pipeline start if memory serves.  Shuttle does follow the *at-least-once* delivery mechanism so it is entirely possible to receive more than one message in some edge cases.  This *may* be what is happening.

You could always give the idemptence service a spin.  There is a [sample](https://github.com/Shuttle/Shuttle.Esb.Samples/tree/master/Shuttle.Idempotence) on how to do this.  It is a purely technical implementation and prevents the same message id from being processed again.  The DB may need some maintenance to clear out old messages I guess but perhaps it is a stop gap measure until the real cause is found; unless it becomes the solution if the issue is an edge case :)

**Comment by claytona-armstrong5** [comment]
Okay, thanks Eben. 
I'm conscious of the possibility of multiple delivery in some edge cases, but I'm hoping you consider this one a fairly typical scenario, and hopefully fixable. I presume once a message has been processed it can be removed from the cache, avoiding the possibility of reprocessing?

For our more critical integrations, involving collection or payment of money, we've built in idempotence... the services actively check for duplicates and take appropriate action. But our collection of integrations has already grown quite quickly over the last few months, and we've not implemented idempotence in all of them due to time constraints. 

Occasional brief database outages are an inevitability for us (even though we are running HA). So that means the present behaviour will always cause double processing in all of our services.

If there's any way it can be avoided in this scenario (where it's just a message poll that fails) it would be greatly appreciated

(But I'll endeavour to ensure we make all future integrations idempotent)

Cheers,
Clayton

**Comment by eben-roux** [comment]
The edge cases should really be quite rare.

In your case, where you are using a Sql table, it actually shouldn't really happen as everything should be wrapped in a transaction )which is configurable).

All the message processing uses "acknowledgement" once the message has been successfully processed (no exception in the handler).  The flow is broadly:

- get a message
- if `null` back-off a bit and then start again
- find handler
- pass message to handler
- if exception then go into retry (possibly via deferred queue); if no more retries move to error queue
- acknowledge message (which removes it from the queue)

All the state remains in the pipeline as the various events/observers are invoked.

In your case killing the DB connection would mean that the message cannot be acknowledged event after it has been completely processed.  It also cannot be requeued for a retry (since the connection is gone).  It will; effectively; stay on the queue until processed... mmm... come to think of it: the "in-process" messages are kept in a collection...

But I'll dig into your scenario when I get some more time.

**Comment by claytona-armstrong5** [comment]
Okay, thanks for the summary of the cycle... that certainly makes sense.

I might not have made it very clear, but it's not necessary to kill the connection during any of the actual processing of the message, or in the middle of the acknowlwdgement procedure.
Rather, I think the issue occurs when the connection is killed at any idle time at all. In our case some of our services had not processed a message for days. In my test to repro it, I probably waited only 20 seconds or so after the service became idle, but I don't think the period matters.  Unless I've misunderstood what's happening, that's why it didn't seem like an edge case... as it wasn't really unfortunate timing, it was inevitable if there was any db outage, even if the services were doing nothing.

**Comment by eben-roux** [comment]
Ah, I see...

I'll keep that in mind, thanks.  That certainly would seem to indicate something is hanging around in memory.  I haven't taken a look at the SqlQueue for quite some time but it would be great to harden it.

I'm just curious: any reason why you guys didn't go for a "real" queue like RabbitMQ or MSMQ?

**Comment by claytona-armstrong5** [comment]
I could be wrong, but I suspect the problem is not actually in the Sql library, but the core one. 
I logged the issue in the Sql lib as I was first thinking the problem was probably there.

We went with sql because it met our needs. It meant we were automatically covered for HA and backups (already sorted in our environment for sql), and avoided needing to roll out something new. The small delays due to the polling are not an issue for us. Using sql allowed us to implement and release a service bus without significant techology change... making the business case for the transition much easier.

If we end up needing to migrate to native queuing, it will probably be RabbitMq.

**Comment by eben-roux** [comment]
I think I may see where an issue may occur.  I assume that you guys are not restarting the services after the errors you describe.  This means that the messages stay in the "cached" *unacknowledged* list and also have not been removed from the queue in the database (as it faulted).  Once the service *does* restart the message would be picked up again and *BOOM*... it is processed again.

Well, it is going to process again in any event once I have moved the processing to first remove from the in-memory list; however, it will be almost immediately.

On which version on the `SqlQueue` are you?  I'm hoping 8.0.0 :)

**Comment by claytona-armstrong5** [comment]
I'm not yet quite in the office to confirm l, but we are probably on 8.0.0 if that's the most recent?

So is the unacknowledged list never cleared?

At the time of the incident triggering, all queues in the database are completely empty, including the error queues... upon the polling exception the old message remateializes (presumably from a  cache), and i assume it then ends up in the deferred queue as a result of the retry?

From memory of the unacknowledged list in SqlQueue, I thought it was only caching identifiers, not the actual messages?

**Comment by claytona-armstrong5** [comment]
I've confirmed, we are using v8.0.0 of SqlQueue

**Comment by claytona-armstrong5** [comment]
A bit more info on this Eben...
It appears that when I tested this yesterday, I got "lucky" the first time I tried it.
The reprocessing appears to not happen every time the connection is killed.  But if I repeatedly kill the connection it consistently happens at some point.  (E.g. maybe one time in 10)
I'm guessing the issue might only occur if the connection issue occurs during the actual read operation.

**Comment by eben-roux** [comment]
You are correct... only keeping a list of Ids.  I'll see if I can dig into it today or possibly over the weekend.

By the way: how do you kill the connection?  I'm assuming simply stopping the relevant Sql instance?

Do you have a simple sample or were you testing from your actual code?  If you have a sample: would you mind e-mailing that to me?  It would be nice to save 5 minutes :)

**Comment by claytona-armstrong5** [comment]
I'm just running "kill nnn" from Management Studio, after identifying the relevant connection. The connection would often come back with the same Id.... I repeatedly killed it until the issue happened.

I was testing using one of our real services, so I don't have stripped down example sorry.

I spent some time looking at the code today trying to identify what was happening, but didn't come up with anything. I did notice that the pipeline factory appears to maintain a pool of pipelines, and the pipelines have their own state cache. I'm speculating that the pipeline being used to read the next message still has the last processed transportmessage set in its state, if it doesn't get cleared upon messages completing processing

**Comment by eben-roux** [comment]
Thanks... sounds like "kill" is SSMS will do the trick.

The first thing the receive pipeline does is to attempt to get a message:

![image](https://user-images.githubusercontent.com/5379436/34431797-b8c0bfc6-ec7a-11e7-9f21-f5848aa2744c.png)

If there is no message the pipeline aborts; else it sets the message:

![image](https://user-images.githubusercontent.com/5379436/34431815-e323754c-ec7a-11e7-8e41-a78b1d715b9c.png)

But I'll have a closer look.  Typically telling yourself that it *should* be working leads one to overlook issues :)

I'm going to be looking at those long parameter lists for the observers in v10 (the one I'm working on now).

**Comment by claytona-armstrong5** [comment]
What is the intended behaviour when queue.GetMessage within the GetWorkMessageObserver generates an exception? I think the exception gets handled by the code that sets up the retries. (Cannot recall the name of that class). And maybe the transportmessage from the previous message is still set in the pipeline state?

**Comment by eben-roux** [comment]
YES!  I think you may be a genius!

The exception is handled in the `ReceiveExceptionObserver` and there is retrieves the current `ReceivedMessage` from the state.  You have spotted it.  The previous message would still be in the state :(

Would you be able to upgrade to the latest version or would you prefer I branch v8.0.0?

There are actually 2 things to fix then:

- I am going to clear the state of the pipline release in the Shuttle.Core.Infrastructure (pipeline factory), and
- remove the message ids before performing the sql operations in the SqlQueue

**Comment by claytona-armstrong5** [comment]
Fantastic! 

If you have time to apply the fix in the 8.0.x line as well as the latest, that would be great. (But understood if it will add too much time)

Many thanks for getting to the bottom of it

Cheers

**Comment by eben-roux** [comment]
Will do... just need to step out for a bit so it should be ready over the weekend.

Apologies for the inconvenience but thanks again for bringing this to my attention.

**Comment by eben-roux** [comment]
Hi Clayton,

OK.  Hopefully this is now sorted with the following:

- https://www.nuget.org/packages/Shuttle.Esb/8.0.13
- https://www.nuget.org/packages/Shuttle.Esb.Sql.Queue/8.0.1

I guess it goes without saying that these should be given a once-over to see that they actually work :)

I apologise for using you as a tester...

**Comment by claytona-armstrong5** [comment]
Fantastic, many thanks for sorting this out Eben.
I'll test it as soon as I can... it will probably not be for a day or so

**Comment by claytona-armstrong5** [comment]
Sorry for the very slow response Eben.
I've just tested the update now, and it looks good to me.  I killed the connection repeatedly, and this time when it failed, it did not reprocess the last message.  Instead the output explicitly indicated that "No message has been received".  And it resumed correct operation once it could connect again.

Thanks again!

**Comment by eben-roux** [comment]
That is excellent news.

Thanks for letting me know.
